build: off
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

configuration: Release
platform:
  - x64

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - echo %PATH%
  - pip install -r requirements-dev.txt
  - fab bootstrap

test_script:
  - python --version
  - fab --version
  - fab test
